### ISSUE TITLE
Update to hybrid 3.0

### ISSUE THREAD

**Issue by emkal** [m-e-h/hybrid_s#1]
Are you going to update hybrid_s  to hybrid 3.0?

**Comment by m-e-h** [comment]
I probably will once 3.0 is stable. Shouldn't be too much longer.
I probably also need to get the _s part caught up with the changes that have taken place with it.

**Comment by emkal** [comment]
Justin mentioned in themehybrids forums that it is already stable.

**Comment by m-e-h** [comment]
updated to 3.0 and the most recent _s
